<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoupleOS.Evals\CoupleOS.Evals.csproj" />
    <ProjectReference Include="..\..\src\CoupleOS.Infrastructure\CoupleOS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CoupleOS.Application\CoupleOS.Application.csproj" />
    <ProjectReference Include="..\..\src\CoupleOS.Api\CoupleOS.Api.csproj" />
  </ItemGroup>

</Project>